apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wuox
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-wuox@sha256:3e45c1ef8b35fa4df168bcd39c101e1180a92633773123e22aa77d87aaa768ce
        name: my-nodejs
        resources: {}
status: {}
